import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1C1C1E',
        justifyContent: 'center',
        alignItems: 'center',
      },
      card: {
        backgroundColor: '#1F1F23',
        width: '90%',
        borderRadius: 20,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#D3D3D3',
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 0 },
        shadowRadius: 10,
        elevation: 10,
      },
      logo: {
        marginBottom: 20,
        height: 100,
        width: 100,
      },
      title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFF',
        marginBottom: 5,
      },
      subtitle: {
        fontSize: 14,
        color: '#D3D3D3', 
        marginBottom: 20,
      },
      inputContainer: {
        width: '100%',
        marginBottom: 15,
      },
      BottomInputStyle: {
        borderBottomWidth: 2,
        borderBottomColor: '#FFF', 
        padding: 10,
        paddingLeft:15,
        fontSize: 16,
        marginTop: 20,
        width: "100%",
        color: '#FFFFFF',
        borderTopRightRadius: 8,
        borderTopLeftRadius: 8,
        backgroundColor: '#292929',
      },
      DarkBlueStandartButton: {
        backgroundColor: '#0047AB', 
        width: 250,
        padding: 15,
        borderRadius: 99999,
        alignItems: 'center',
        marginBottom: 20,
        marginTop: 20,
        shadowColor: '#000',
        shadowRadius: 10,
        elevation: 10,
        shadowColor: '#000',
        shadowRadius: 10,
        elevation: 10,
      },
      loginButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
      },
      signup: {
        color: '#D3D3D3',
      },
      signupText: {
        color: '#FFF',
        fontWeight: 'bold',
      },
      errorText: {
        color: '#FF3131',
        fontWeight: 'bold',
        position: 'absolute',
        bottom: "5%",
        left: 20,
        right: 20,
        textAlign: 'center',
      },
      confirmText: {
        color: '#8bc34a',
        fontWeight: 'bold',
        position: 'absolute',
        bottom: "5%",
        left: 20,
        right: 20,
        textAlign: 'center',
      },
});
