import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({

      BlueStandartButton: {
        backgroundColor: '#007BFF',
        padding: 12,
        borderRadius: 9999,
        alignItems: 'center',
        alignSelf: 'center',
        width: 130,
        shadowColor: '#000',
        shadowRadius: 10,
        elevation: 10,
      },
      OrangeStandartButton: {
        backgroundColor: '#FF4500',
        padding: 12,
        borderRadius: 9999,
        alignItems: 'center',
        alignSelf: 'center',
        marginTop: 16,
        width: 130,
        shadowColor: '#000',
        shadowRadius: 10,
        elevation: 10,
      },
      DarkBlueStandartButton: {
        backgroundColor: '#0047AB', 
        width: 250,
        padding: 15,
        borderRadius: 99999,
        alignItems: 'center',
        marginBottom: 20,
        marginTop: 20,
        shadowColor: '#000',
        shadowRadius: 10,
        elevation: 10,
      },
      BorderButtonStyle:{
        backgroundColor: 'transparent',
        paddingVertical: 8,
        paddingHorizontal: 20,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#696868',
        width: 130,
      },
      //X Kapatma Butonu
      X_CloseButton: {
        position: 'absolute',
        top: 20,
        right: 20,
    },
    GreenCirclePickerButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#4CAF50',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowRadius: 10,
        elevation: 10,
      },
      GreenCirclePickerButtonMini: {
        width: 40,
        height: 40,
        borderRadius: 25,
        backgroundColor: '#4CAF50',
        justifyContent: 'center',
        alignItems: 'center',
      },
      BlueCirlePickerButon: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#007bff',
        padding: 10,
        marginHorizontal:10,
        borderRadius: 20,
        width: 40,  
        height: 40,
      },
      OrangeCirclePickerButton: {
        backgroundColor: '#FF8C00',
        position: 'absolute',
        bottom: 20,
        alignSelf: 'center',
        padding: 15,
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 5,
        elevation: 5,
        zIndex: 2,
      },
      
});

export default styles;
